import { artists } from "./artists-data.js";

export const playlist = [
  {
    id: 1,
    song: artists[17].albums[0].songs[1].title,
    artist: artists[17].name,
    album: artists[17].albums[0].title,
    duration: artists[17].albums[0].songs[1].duration,
    released: artists[17].albums[0].released,
  },
  {
    id: 2,
    song: artists[15].albums[3].songs[0].title,
    artist: artists[15].name,
    album: artists[15].albums[3].title,
    duration: artists[15].albums[3].songs[0].duration,
    released: artists[15].albums[3].released,
  },
  {
    id: 3,
    song: artists[18].albums[2].songs[0].title,
    artist: artists[18].name,
    album: artists[18].albums[2].title,
    duration: artists[18].albums[2].songs[0].duration,
    released: artists[18].albums[2].released,
  },
  {
    id: 4,
    song: artists[6].albums[0].songs[3].title,
    artist: artists[6].name,
    album: artists[6].albums[0].title,
    duration: artists[6].albums[0].songs[3].duration,
    released: artists[6].albums[0].released,
  },
  {
    id: 5,
    song: artists[19].albums[0].songs[5].title,
    artist: artists[19].name,
    album: artists[19].albums[0].title,
    duration: artists[19].albums[0].songs[5].duration,
    released: artists[19].albums[0].released,
  },
  {
    id: 6,
    song: artists[1].albums[0].songs[2].title,
    artist: artists[1].name,
    album: artists[1].albums[0].title,
    duration: artists[1].albums[0].songs[2].duration,
    released: artists[1].albums[0].released,
  },
  {
    id: 7,
    song: artists[20].albums[3].songs[1].title,
    artist: artists[20].name,
    album: artists[20].albums[3].title,
    duration: artists[20].albums[3].songs[1].duration,
    released: artists[20].albums[3].released,
  },
  {
    id: 8,
    song: artists[17].albums[1].songs[0].title,
    artist: artists[17].name,
    album: artists[17].albums[1].title,
    duration: artists[17].albums[1].songs[0].duration,
    released: artists[17].albums[1].released,
  },
  {
    id: 9,
    song: artists[3].albums[0].songs[2].title,
    artist: artists[3].name,
    album: artists[3].albums[0].title,
    duration: artists[3].albums[0].songs[2].duration,
    released: artists[3].albums[0].released,
  },
  {
    id: 10,
    song: artists[4].albums[6].songs[0].title,
    artist: artists[4].name,
    album: artists[4].albums[6].title,
    duration: artists[4].albums[6].songs[0].duration,
    released: artists[4].albums[6].released,
  },
  {
    id: 11,
    song: artists[16].albums[2].songs[1].title,
    artist: artists[16].name,
    album: artists[16].albums[2].title,
    duration: artists[16].albums[2].songs[1].duration,
    released: artists[16].albums[2].released,
  },
  {
    id: 12,
    song: artists[10].albums[2].songs[0].title,
    artist: artists[10].name,
    album: artists[10].albums[2].title,
    duration: artists[10].albums[2].songs[0].duration,
    released: artists[10].albums[2].released,
  },
  {
    id: 13,
    song: artists[9].albums[0].songs[1].title,
    artist: artists[9].name,
    album: artists[9].albums[0].title,
    duration: artists[9].albums[0].songs[1].duration,
    released: artists[9].albums[0].released,
  },
  {
    id: 14,
    song: artists[21].albums[2].songs[4].title,
    artist: artists[21].name,
    album: artists[21].albums[2].title,
    duration: artists[21].albums[2].songs[4].duration,
    released: artists[21].albums[2].released,
  },
  {
    id: 15,
    song: artists[7].albums[0].songs[2].title,
    artist: artists[7].name,
    album: artists[7].albums[0].title,
    duration: artists[7].albums[0].songs[2].duration,
    released: artists[7].albums[0].released,
  },
  {
    id: 16,
    song: artists[2].albums[1].songs[0].title,
    artist: artists[2].name,
    album: artists[2].albums[1].title,
    duration: artists[2].albums[1].songs[0].duration,
    released: artists[2].albums[1].released,
  },
  {
    id: 17,
    song: artists[19].albums[1].songs[1].title,
    artist: artists[19].name,
    album: artists[19].albums[1].title,
    duration: artists[19].albums[1].songs[1].duration,
    released: artists[19].albums[1].released,
  },
  {
    id: 18,
    song: artists[21].albums[2].songs[3].title,
    artist: artists[21].name,
    album: artists[21].albums[2].title,
    duration: artists[21].albums[2].songs[3].duration,
    released: artists[21].albums[2].released,
  },
  {
    id: 19,
    song: artists[12].albums[0].songs[1].title,
    artist: artists[12].name,
    album: artists[12].albums[0].title,
    duration: artists[12].albums[0].songs[1].duration,
    released: artists[12].albums[0].released,
  },
  {
    id: 20,
    song: artists[7].albums[1].songs[1].title,
    artist: artists[7].name,
    album: artists[7].albums[1].title,
    duration: artists[7].albums[1].songs[1].duration,
    released: artists[7].albums[1].released,
  },
  {
    id: 21,
    song: artists[1].albums[0].songs[5].title,
    artist: artists[1].name,
    album: artists[1].albums[0].title,
    duration: artists[1].albums[0].songs[5].duration,
    released: artists[1].albums[0].released,
  },
  {
    id: 22,
    song: artists[4].albums[3].songs[0].title,
    artist: artists[4].name,
    album: artists[4].albums[3].title,
    duration: artists[4].albums[3].songs[0].duration,
    released: artists[4].albums[3].released,
  },
  {
    id: 23,
    song: artists[2].albums[1].songs[2].title,
    artist: artists[2].name,
    album: artists[2].albums[1].title,
    duration: artists[2].albums[1].songs[2].duration,
    released: artists[2].albums[1].released,
  },
  {
    id: 24,
    song: artists[11].albums[0].songs[0].title,
    artist: artists[11].name,
    album: artists[11].albums[0].title,
    duration: artists[11].albums[0].songs[0].duration,
    released: artists[11].albums[0].released,
  },
  {
    id: 25,
    song: artists[3].albums[0].songs[1].title,
    artist: artists[3].name,
    album: artists[3].albums[0].title,
    duration: artists[3].albums[0].songs[1].duration,
    released: artists[3].albums[0].released,
  },
  {
    id: 26,
    song: artists[7].albums[0].songs[0].title,
    artist: artists[7].name,
    album: artists[7].albums[0].title,
    duration: artists[7].albums[0].songs[0].duration,
    released: artists[7].albums[0].released,
  },
  {
    id: 27,
    song: artists[16].albums[0].songs[1].title,
    artist: artists[16].name,
    album: artists[16].albums[0].title,
    duration: artists[16].albums[0].songs[1].duration,
    released: artists[16].albums[0].released,
  },
  {
    id: 28,
    song: artists[9].albums[0].songs[4].title,
    artist: artists[9].name,
    album: artists[9].albums[0].title,
    duration: artists[9].albums[0].songs[4].duration,
    released: artists[9].albums[0].released,
  },
  {
    id: 29,
    song: artists[18].albums[3].songs[1].title,
    artist: artists[18].name,
    album: artists[18].albums[3].title,
    duration: artists[18].albums[3].songs[1].duration,
    released: artists[18].albums[3].released,
  },
  {
    id: 30,
    song: artists[15].albums[1].songs[1].title,
    artist: artists[15].name,
    album: artists[15].albums[1].title,
    duration: artists[15].albums[1].songs[1].duration,
    released: artists[15].albums[1].released,
  },
  {
    id: 31,
    song: artists[4].albums[5].songs[0].title,
    artist: artists[4].name,
    album: artists[4].albums[5].title,
    duration: artists[4].albums[5].songs[0].duration,
    released: artists[4].albums[5].released,
  },
  {
    id: 32,
    song: artists[11].albums[0].songs[2].title,
    artist: artists[11].name,
    album: artists[11].albums[0].title,
    duration: artists[11].albums[0].songs[2].duration,
    released: artists[11].albums[0].released,
  },
  {
    id: 33,
    song: artists[16].albums[0].songs[3].title,
    artist: artists[16].name,
    album: artists[16].albums[0].title,
    duration: artists[16].albums[0].songs[3].duration,
    released: artists[16].albums[0].released,
  },
  {
    id: 34,
    song: artists[8].albums[2].songs[1].title,
    artist: artists[8].name,
    album: artists[8].albums[2].title,
    duration: artists[8].albums[2].songs[1].duration,
    released: artists[8].albums[2].released,
  },
  {
    id: 35,
    song: artists[19].albums[0].songs[1].title,
    artist: artists[19].name,
    album: artists[19].albums[0].title,
    duration: artists[19].albums[0].songs[1].duration,
    released: artists[19].albums[0].released,
  },
  {
    id: 36,
    song: artists[1].albums[1].songs[0].title,
    artist: artists[1].name,
    album: artists[1].albums[1].title,
    duration: artists[1].albums[1].songs[0].duration,
    released: artists[1].albums[1].released,
  },
  {
    id: 37,
    song: artists[10].albums[1].songs[1].title,
    artist: artists[10].name,
    album: artists[10].albums[1].title,
    duration: artists[10].albums[1].songs[1].duration,
    released: artists[10].albums[1].released,
  },
  {
    id: 38,
    song: artists[17].albums[2].songs[2].title,
    artist: artists[17].name,
    album: artists[17].albums[2].title,
    duration: artists[17].albums[2].songs[2].duration,
    released: artists[17].albums[2].released,
  },
  {
    id: 39,
    song: artists[15].albums[4].songs[0].title,
    artist: artists[15].name,
    album: artists[15].albums[4].title,
    duration: artists[15].albums[4].songs[0].duration,
    released: artists[15].albums[4].released,
  },
  {
    id: 40,
    song: artists[12].albums[0].songs[2].title,
    artist: artists[12].name,
    album: artists[12].albums[0].title,
    duration: artists[12].albums[0].songs[2].duration,
    released: artists[12].albums[0].released,
  },
  {
    id: 41,
    song: artists[10].albums[2].songs[1].title,
    artist: artists[10].name,
    album: artists[10].albums[2].title,
    duration: artists[10].albums[2].songs[1].duration,
    released: artists[10].albums[2].released,
  },
  {
    id: 42,
    song: artists[2].albums[0].songs[4].title,
    artist: artists[2].name,
    album: artists[2].albums[0].title,
    duration: artists[2].albums[0].songs[4].duration,
    released: artists[2].albums[0].released,
  },
  {
    id: 43,
    song: artists[19].albums[1].songs[3].title,
    artist: artists[19].name,
    album: artists[19].albums[1].title,
    duration: artists[19].albums[1].songs[3].duration,
    released: artists[19].albums[1].released,
  },
  {
    id: 44,
    song: artists[5].albums[0].songs[1].title,
    artist: artists[5].name,
    album: artists[5].albums[0].title,
    duration: artists[5].albums[0].songs[1].duration,
    released: artists[5].albums[0].released,
  },
  {
    id: 45,
    song: artists[1].albums[1].songs[2].title,
    artist: artists[1].name,
    album: artists[1].albums[1].title,
    duration: artists[1].albums[1].songs[2].duration,
    released: artists[1].albums[1].released,
  },
  {
    id: 46,
    song: artists[12].albums[0].songs[5].title,
    artist: artists[12].name,
    album: artists[12].albums[0].title,
    duration: artists[12].albums[0].songs[5].duration,
    released: artists[12].albums[0].released,
  },
  {
    id: 47,
    song: artists[3].albums[1].songs[0].title,
    artist: artists[3].name,
    album: artists[3].albums[1].title,
    duration: artists[3].albums[1].songs[0].duration,
    released: artists[3].albums[1].released,
  },
  {
    id: 48,
    song: artists[16].albums[0].songs[2].title,
    artist: artists[16].name,
    album: artists[16].albums[0].title,
    duration: artists[16].albums[0].songs[2].duration,
    released: artists[16].albums[0].released,
  },
  {
    id: 49,
    song: artists[2].albums[0].songs[1].title,
    artist: artists[2].name,
    album: artists[2].albums[0].title,
    duration: artists[2].albums[0].songs[1].duration,
    released: artists[2].albums[0].released,
  },
  {
    id: 50,
    song: artists[4].albums[2].songs[0].title,
    artist: artists[4].name,
    album: artists[4].albums[2].title,
    duration: artists[4].albums[2].songs[0].duration,
    released: artists[4].albums[2].released,
  },
  {
    id: 51,
    song: artists[8].albums[2].songs[3].title,
    artist: artists[8].name,
    album: artists[8].albums[2].title,
    duration: artists[8].albums[2].songs[3].duration,
    released: artists[8].albums[2].released,
  },
  {
    id: 52,
    song: artists[13].albums[0].songs[1].title,
    artist: artists[13].name,
    album: artists[13].albums[0].title,
    duration: artists[13].albums[0].songs[1].duration,
    released: artists[13].albums[0].released,
  },
  {
    id: 53,
    song: artists[20].albums[3].songs[0].title,
    artist: artists[20].name,
    album: artists[20].albums[3].title,
    duration: artists[20].albums[3].songs[0].duration,
    released: artists[20].albums[3].released,
  },
  {
    id: 54,
    song: artists[9].albums[0].songs[3].title,
    artist: artists[9].name,
    album: artists[9].albums[0].title,
    duration: artists[9].albums[0].songs[3].duration,
    released: artists[9].albums[0].released,
  },
  {
    id: 55,
    song: artists[10].albums[2].songs[2].title,
    artist: artists[10].name,
    album: artists[10].albums[2].title,
    duration: artists[10].albums[2].songs[2].duration,
    released: artists[10].albums[2].released,
  },
  {
    id: 56,
    song: artists[18].albums[0].songs[1].title,
    artist: artists[18].name,
    album: artists[18].albums[0].title,
    duration: artists[18].albums[0].songs[1].duration,
    released: artists[18].albums[0].released,
  },
  {
    id: 57,
    song: artists[21].albums[0].songs[1].title,
    artist: artists[21].name,
    album: artists[21].albums[0].title,
    duration: artists[21].albums[0].songs[1].duration,
    released: artists[21].albums[0].released,
  },
  {
    id: 58,
    song: artists[4].albums[4].songs[1].title,
    artist: artists[4].name,
    album: artists[4].albums[4].title,
    duration: artists[4].albums[4].songs[1].duration,
    released: artists[4].albums[4].released,
  },
  {
    id: 59,
    song: artists[1].albums[1].songs[1].title,
    artist: artists[1].name,
    album: artists[1].albums[1].title,
    duration: artists[1].albums[1].songs[1].duration,
    released: artists[1].albums[1].released,
  },
  {
    id: 60,
    song: artists[20].albums[1].songs[1].title,
    artist: artists[20].name,
    album: artists[20].albums[1].title,
    duration: artists[20].albums[1].songs[1].duration,
    released: artists[20].albums[1].released,
  },
  {
    id: 61,
    song: artists[6].albums[0].songs[1].title,
    artist: artists[6].name,
    album: artists[6].albums[0].title,
    duration: artists[6].albums[0].songs[1].duration,
    released: artists[6].albums[0].released,
  },
  {
    id: 62,
    song: artists[15].albums[4].songs[1].title,
    artist: artists[15].name,
    album: artists[15].albums[4].title,
    duration: artists[15].albums[4].songs[1].duration,
    released: artists[15].albums[4].released,
  },
  {
    id: 63,
    song: artists[19].albums[0].songs[0].title,
    artist: artists[19].name,
    album: artists[19].albums[0].title,
    duration: artists[19].albums[0].songs[0].duration,
    released: artists[19].albums[0].released,
  },
  {
    id: 64,
    song: artists[9].albums[2].songs[0].title,
    artist: artists[9].name,
    album: artists[9].albums[2].title,
    duration: artists[9].albums[2].songs[0].duration,
    released: artists[9].albums[2].released,
  },
  {
    id: 65,
    song: artists[17].albums[2].songs[1].title,
    artist: artists[17].name,
    album: artists[17].albums[2].title,
    duration: artists[17].albums[2].songs[1].duration,
    released: artists[17].albums[2].released,
  },
  {
    id: 66,
    song: artists[1].albums[0].songs[3].title,
    artist: artists[1].name,
    album: artists[1].albums[0].title,
    duration: artists[1].albums[0].songs[3].duration,
    released: artists[1].albums[0].released,
  },
  {
    id: 67,
    song: artists[19].albums[0].songs[3].title,
    artist: artists[19].name,
    album: artists[19].albums[0].title,
    duration: artists[19].albums[0].songs[3].duration,
    released: artists[19].albums[0].released,
  },
  {
    id: 68,
    song: artists[15].albums[2].songs[0].title,
    artist: artists[15].name,
    album: artists[15].albums[2].title,
    duration: artists[15].albums[2].songs[0].duration,
    released: artists[15].albums[2].released,
  },
  {
    id: 69,
    song: artists[6].albums[0].songs[2].title,
    artist: artists[6].name,
    album: artists[6].albums[0].title,
    duration: artists[6].albums[0].songs[2].duration,
    released: artists[6].albums[0].released,
  },
  {
    id: 70,
    song: artists[17].albums[3].songs[1].title,
    artist: artists[17].name,
    album: artists[17].albums[3].title,
    duration: artists[17].albums[3].songs[1].duration,
    released: artists[17].albums[3].released,
  },
  {
    id: 71,
    song: artists[20].albums[0].songs[2].title,
    artist: artists[20].name,
    album: artists[20].albums[0].title,
    duration: artists[20].albums[0].songs[2].duration,
    released: artists[20].albums[0].released,
  },
  {
    id: 72,
    song: artists[2].albums[1].songs[3].title,
    artist: artists[2].name,
    album: artists[2].albums[1].title,
    duration: artists[2].albums[1].songs[3].duration,
    released: artists[2].albums[1].released,
  },
  {
    id: 73,
    song: artists[10].albums[0].songs[0].title,
    artist: artists[10].name,
    album: artists[10].albums[0].title,
    duration: artists[10].albums[0].songs[0].duration,
    released: artists[10].albums[0].released,
  },
  {
    id: 74,
    song: artists[18].albums[0].songs[2].title,
    artist: artists[18].name,
    album: artists[18].albums[0].title,
    duration: artists[18].albums[0].songs[2].duration,
    released: artists[18].albums[0].released,
  },
  {
    id: 75,
    song: artists[21].albums[0].songs[0].title,
    artist: artists[21].name,
    album: artists[21].albums[0].title,
    duration: artists[21].albums[0].songs[0].duration,
    released: artists[21].albums[0].released,
  },
  {
    id: 76,
    song: artists[3].albums[0].songs[3].title,
    artist: artists[3].name,
    album: artists[3].albums[0].title,
    duration: artists[3].albums[0].songs[3].duration,
    released: artists[3].albums[0].released,
  },
  {
    id: 77,
    song: artists[7].albums[0].songs[3].title,
    artist: artists[7].name,
    album: artists[7].albums[0].title,
    duration: artists[7].albums[0].songs[3].duration,
    released: artists[7].albums[0].released,
  },
  {
    id: 78,
    song: artists[9].albums[0].songs[0].title,
    artist: artists[9].name,
    album: artists[9].albums[0].title,
    duration: artists[9].albums[0].songs[0].duration,
    released: artists[9].albums[0].released,
  },
  {
    id: 79,
    song: artists[18].albums[2].songs[2].title,
    artist: artists[18].name,
    album: artists[18].albums[2].title,
    duration: artists[18].albums[2].songs[2].duration,
    released: artists[18].albums[2].released,
  },
  {
    id: 80,
    song: artists[6].albums[1].songs[1].title,
    artist: artists[6].name,
    album: artists[6].albums[1].title,
    duration: artists[6].albums[1].songs[1].duration,
    released: artists[6].albums[1].released,
  },
  {
    id: 81,
    song: artists[20].albums[0].songs[0].title,
    artist: artists[20].name,
    album: artists[20].albums[0].title,
    duration: artists[20].albums[0].songs[0].duration,
    released: artists[20].albums[0].released,
  },
  {
    id: 82,
    song: artists[17].albums[0].songs[0].title,
    artist: artists[17].name,
    album: artists[17].albums[0].title,
    duration: artists[17].albums[0].songs[0].duration,
    released: artists[17].albums[0].released,
  },
  {
    id: 83,
    song: artists[15].albums[1].songs[3].title,
    artist: artists[15].name,
    album: artists[15].albums[1].title,
    duration: artists[15].albums[1].songs[3].duration,
    released: artists[15].albums[1].released,
  },
  {
    id: 84,
    song: artists[21].albums[2].songs[2].title,
    artist: artists[21].name,
    album: artists[21].albums[2].title,
    duration: artists[21].albums[2].songs[2].duration,
    released: artists[21].albums[2].released,
  },
  {
    id: 85,
    song: artists[18].albums[0].songs[3].title,
    artist: artists[18].name,
    album: artists[18].albums[0].title,
    duration: artists[18].albums[0].songs[3].duration,
    released: artists[18].albums[0].released,
  },
  {
    id: 86,
    song: artists[9].albums[0].songs[6].title,
    artist: artists[9].name,
    album: artists[9].albums[0].title,
    duration: artists[9].albums[0].songs[6].duration,
    released: artists[9].albums[0].released,
  },
  {
    id: 87,
    song: artists[4].albums[0].songs[0].title,
    artist: artists[4].name,
    album: artists[4].albums[0].title,
    duration: artists[4].albums[0].songs[0].duration,
    released: artists[4].albums[0].released,
  },
  {
    id: 88,
    song: artists[7].albums[0].songs[1].title,
    artist: artists[7].name,
    album: artists[7].albums[0].title,
    duration: artists[7].albums[0].songs[1].duration,
    released: artists[7].albums[0].released,
  },
  {
    id: 89,
    song: artists[9].albums[0].songs[2].title,
    artist: artists[9].name,
    album: artists[9].albums[0].title,
    duration: artists[9].albums[0].songs[2].duration,
    released: artists[9].albums[0].released,
  },
  {
    id: 90,
    song: artists[21].albums[3].songs[0].title,
    artist: artists[21].name,
    album: artists[21].albums[3].title,
    duration: artists[21].albums[3].songs[0].duration,
    released: artists[21].albums[3].released,
  },
  {
    id: 91,
    song: artists[11].albums[0].songs[1].title,
    artist: artists[11].name,
    album: artists[11].albums[0].title,
    duration: artists[11].albums[0].songs[1].duration,
    released: artists[11].albums[0].released,
  },
  {
    id: 92,
    song: artists[15].albums[1].songs[2].title,
    artist: artists[15].name,
    album: artists[15].albums[1].title,
    duration: artists[15].albums[1].songs[2].duration,
    released: artists[15].albums[1].released,
  },
  {
    id: 93,
    song: artists[19].albums[0].songs[4].title,
    artist: artists[19].name,
    album: artists[19].albums[0].title,
    duration: artists[19].albums[0].songs[4].duration,
    released: artists[19].albums[0].released,
  },
  {
    id: 94,
    song: artists[12].albums[0].songs[3].title,
    artist: artists[12].name,
    album: artists[12].albums[0].title,
    duration: artists[12].albums[0].songs[3].duration,
    released: artists[12].albums[0].released,
  },
  {
    id: 95,
    song: artists[4].albums[1].songs[0].title,
    artist: artists[4].name,
    album: artists[4].albums[1].title,
    duration: artists[4].albums[1].songs[0].duration,
    released: artists[4].albums[1].released,
  },
  {
    id: 96,
    song: artists[7].albums[0].songs[4].title,
    artist: artists[7].name,
    album: artists[7].albums[0].title,
    duration: artists[7].albums[0].songs[4].duration,
    released: artists[7].albums[0].released,
  },
  {
    id: 97,
    song: artists[2].albums[1].songs[1].title,
    artist: artists[2].name,
    album: artists[2].albums[1].title,
    duration: artists[2].albums[1].songs[1].duration,
    released: artists[2].albums[1].released,
  },
  {
    id: 98,
    song: artists[8].albums[1].songs[0].title,
    artist: artists[8].name,
    album: artists[8].albums[1].title,
    duration: artists[8].albums[1].songs[0].duration,
    released: artists[8].albums[1].released,
  },
  {
    id: 99,
    song: artists[13].albums[1].songs[0].title,
    artist: artists[13].name,
    album: artists[13].albums[1].title,
    duration: artists[13].albums[1].songs[0].duration,
    released: artists[13].albums[1].released,
  },
  {
    id: 100,
    song: artists[17].albums[3].songs[2].title,
    artist: artists[17].name,
    album: artists[17].albums[3].title,
    duration: artists[17].albums[3].songs[2].duration,
    released: artists[17].albums[3].released,
  },
  {
    id: 101,
    song: artists[15].albums[0].songs[0].title,
    artist: artists[15].name,
    album: artists[15].albums[0].title,
    duration: artists[15].albums[0].songs[0].duration,
    released: artists[15].albums[0].released,
  },
  {
    id: 102,
    song: artists[8].albums[3].songs[0].title,
    artist: artists[8].name,
    album: artists[8].albums[3].title,
    duration: artists[8].albums[3].songs[0].duration,
    released: artists[8].albums[3].released,
  },
  {
    id: 103,
    song: artists[7].albums[1].songs[0].title,
    artist: artists[7].name,
    album: artists[7].albums[1].title,
    duration: artists[7].albums[1].songs[0].duration,
    released: artists[7].albums[1].released,
  },
  {
    id: 104,
    song: artists[4].albums[3].songs[1].title,
    artist: artists[4].name,
    album: artists[4].albums[3].title,
    duration: artists[4].albums[3].songs[1].duration,
    released: artists[4].albums[3].released,
  },
  {
    id: 105,
    song: artists[12].albums[0].songs[0].title,
    artist: artists[12].name,
    album: artists[12].albums[0].title,
    duration: artists[12].albums[0].songs[0].duration,
    released: artists[12].albums[0].released,
  },
  {
    id: 106,
    song: artists[1].albums[0].songs[0].title,
    artist: artists[1].name,
    album: artists[1].albums[0].title,
    duration: artists[1].albums[0].songs[0].duration,
    released: artists[1].albums[0].released,
  },
  {
    id: 107,
    song: artists[8].albums[0].songs[0].title,
    artist: artists[8].name,
    album: artists[8].albums[0].title,
    duration: artists[8].albums[0].songs[0].duration,
    released: artists[8].albums[0].released,
  },
  {
    id: 108,
    song: artists[10].albums[2].songs[5].title,
    artist: artists[10].name,
    album: artists[10].albums[2].title,
    duration: artists[10].albums[2].songs[5].duration,
    released: artists[10].albums[2].released,
  },
  {
    id: 109,
    song: artists[19].albums[1].songs[0].title,
    artist: artists[19].name,
    album: artists[19].albums[1].title,
    duration: artists[19].albums[1].songs[0].duration,
    released: artists[19].albums[1].released,
  },
  {
    id: 110,
    song: artists[5].albums[0].songs[0].title,
    artist: artists[5].name,
    album: artists[5].albums[0].title,
    duration: artists[5].albums[0].songs[0].duration,
    released: artists[5].albums[0].released,
  },
  {
    id: 111,
    song: artists[16].albums[0].songs[0].title,
    artist: artists[16].name,
    album: artists[16].albums[0].title,
    duration: artists[16].albums[0].songs[0].duration,
    released: artists[16].albums[0].released,
  },
  {
    id: 112,
    song: artists[20].albums[2].songs[1].title,
    artist: artists[20].name,
    album: artists[20].albums[2].title,
    duration: artists[20].albums[2].songs[1].duration,
    released: artists[20].albums[2].released,
  },
  {
    id: 113,
    song: artists[2].albums[0].songs[0].title,
    artist: artists[2].name,
    album: artists[2].albums[0].title,
    duration: artists[2].albums[0].songs[0].duration,
    released: artists[2].albums[0].released,
  },
  {
    id: 114,
    song: artists[12].albums[1].songs[0].title,
    artist: artists[12].name,
    album: artists[12].albums[1].title,
    duration: artists[12].albums[1].songs[0].duration,
    released: artists[12].albums[1].released,
  },
  {
    id: 115,
    song: artists[10].albums[1].songs[0].title,
    artist: artists[10].name,
    album: artists[10].albums[1].title,
    duration: artists[10].albums[1].songs[0].duration,
    released: artists[10].albums[1].released,
  },
  {
    id: 116,
    song: artists[8].albums[2].songs[0].title,
    artist: artists[8].name,
    album: artists[8].albums[2].title,
    duration: artists[8].albums[2].songs[0].duration,
    released: artists[8].albums[2].released,
  },
  {
    id: 117,
    song: artists[2].albums[0].songs[3].title,
    artist: artists[2].name,
    album: artists[2].albums[0].title,
    duration: artists[2].albums[0].songs[3].duration,
    released: artists[2].albums[0].released,
  },
  {
    id: 118,
    song: artists[13].albums[1].songs[2].title,
    artist: artists[13].name,
    album: artists[13].albums[1].title,
    duration: artists[13].albums[1].songs[2].duration,
    released: artists[13].albums[1].released,
  },
  {
    id: 119,
    song: artists[5].albums[0].songs[2].title,
    artist: artists[5].name,
    album: artists[5].albums[0].title,
    duration: artists[5].albums[0].songs[2].duration,
    released: artists[5].albums[0].released,
  },
  {
    id: 120,
    song: artists[20].albums[2].songs[0].title,
    artist: artists[20].name,
    album: artists[20].albums[2].title,
    duration: artists[20].albums[2].songs[0].duration,
    released: artists[20].albums[2].released,
  },
  {
    id: 121,
    song: artists[15].albums[4].songs[2].title,
    artist: artists[15].name,
    album: artists[15].albums[4].title,
    duration: artists[15].albums[4].songs[2].duration,
    released: artists[15].albums[4].released,
  },
  {
    id: 122,
    song: artists[18].albums[0].songs[0].title,
    artist: artists[18].name,
    album: artists[18].albums[0].title,
    duration: artists[18].albums[0].songs[0].duration,
    released: artists[18].albums[0].released,
  },
  {
    id: 123,
    song: artists[13].albums[1].songs[1].title,
    artist: artists[13].name,
    album: artists[13].albums[1].title,
    duration: artists[13].albums[1].songs[1].duration,
    released: artists[13].albums[1].released,
  },
  {
    id: 124,
    song: artists[10].albums[1].songs[2].title,
    artist: artists[10].name,
    album: artists[10].albums[1].title,
    duration: artists[10].albums[1].songs[2].duration,
    released: artists[10].albums[1].released,
  },
  {
    id: 125,
    song: artists[1].albums[0].songs[1].title,
    artist: artists[1].name,
    album: artists[1].albums[0].title,
    duration: artists[1].albums[0].songs[1].duration,
    released: artists[1].albums[0].released,
  },
  {
    id: 126,
    song: artists[17].albums[2].songs[0].title,
    artist: artists[17].name,
    album: artists[17].albums[2].title,
    duration: artists[17].albums[2].songs[0].duration,
    released: artists[17].albums[2].released,
  },
  {
    id: 127,
    song: artists[20].albums[0].songs[1].title,
    artist: artists[20].name,
    album: artists[20].albums[0].title,
    duration: artists[20].albums[0].songs[1].duration,
    released: artists[20].albums[0].released,
  },
  {
    id: 128,
    song: artists[6].albums[1].songs[0].title,
    artist: artists[6].name,
    album: artists[6].albums[1].title,
    duration: artists[6].albums[1].songs[0].duration,
    released: artists[6].albums[1].released,
  },
  {
    id: 129,
    song: artists[16].albums[2].songs[1].title,
    artist: artists[16].name,
    album: artists[16].albums[2].title,
    duration: artists[16].albums[2].songs[1].duration,
    released: artists[16].albums[2].released,
  },
  {
    id: 130,
    song: artists[18].albums[1].songs[0].title,
    artist: artists[18].name,
    album: artists[18].albums[1].title,
    duration: artists[18].albums[1].songs[0].duration,
    released: artists[18].albums[1].released,
  },
  {
    id: 131,
    song: artists[20].albums[1].songs[0].title,
    artist: artists[20].name,
    album: artists[20].albums[1].title,
    duration: artists[20].albums[1].songs[0].duration,
    released: artists[20].albums[1].released,
  },
  {
    id: 132,
    song: artists[17].albums[3].songs[0].title,
    artist: artists[17].name,
    album: artists[17].albums[3].title,
    duration: artists[17].albums[3].songs[0].duration,
    released: artists[17].albums[3].released,
  },
  {
    id: 133,
    song: artists[13].albums[0].songs[0].title,
    artist: artists[13].name,
    album: artists[13].albums[0].title,
    duration: artists[13].albums[0].songs[0].duration,
    released: artists[13].albums[0].released,
  },
  {
    id: 134,
    song: artists[21].albums[2].songs[0].title,
    artist: artists[21].name,
    album: artists[21].albums[2].title,
    duration: artists[21].albums[2].songs[0].duration,
    released: artists[21].albums[2].released,
  },
  {
    id: 135,
    song: artists[15].albums[1].songs[0].title,
    artist: artists[15].name,
    album: artists[15].albums[1].title,
    duration: artists[15].albums[1].songs[0].duration,
    released: artists[15].albums[1].released,
  },
  {
    id: 136,
    song: artists[8].albums[2].songs[2].title,
    artist: artists[8].name,
    album: artists[8].albums[2].title,
    duration: artists[8].albums[2].songs[2].duration,
    released: artists[8].albums[2].released,
  },
  {
    id: 137,
    song: artists[9].albums[0].songs[5].title,
    artist: artists[9].name,
    album: artists[9].albums[0].title,
    duration: artists[9].albums[0].songs[5].duration,
    released: artists[9].albums[0].released,
  },
  {
    id: 138,
    song: artists[4].albums[4].songs[2].title,
    artist: artists[4].name,
    album: artists[4].albums[4].title,
    duration: artists[4].albums[4].songs[2].duration,
    released: artists[4].albums[4].released,
  },
  {
    id: 139,
    song: artists[7].albums[0].songs[5].title,
    artist: artists[7].name,
    album: artists[7].albums[0].title,
    duration: artists[7].albums[0].songs[5].duration,
    released: artists[7].albums[0].released,
  },
  {
    id: 140,
    song: artists[12].albums[0].songs[4].title,
    artist: artists[12].name,
    album: artists[12].albums[0].title,
    duration: artists[12].albums[0].songs[4].duration,
    released: artists[12].albums[0].released,
  },
  {
    id: 141,
    song: artists[10].albums[2].songs[3].title,
    artist: artists[10].name,
    album: artists[10].albums[2].title,
    duration: artists[10].albums[2].songs[3].duration,
    released: artists[10].albums[2].released,
  },
  {
    id: 142,
    song: artists[8].albums[2].songs[4].title,
    artist: artists[8].name,
    album: artists[8].albums[2].title,
    duration: artists[8].albums[2].songs[4].duration,
    released: artists[8].albums[2].released,
  },
  {
    id: 143,
    song: artists[3].albums[0].songs[0].title,
    artist: artists[3].name,
    album: artists[3].albums[0].title,
    duration: artists[3].albums[0].songs[0].duration,
    released: artists[3].albums[0].released,
  },
  {
    id: 144,
    song: artists[14].albums[0].songs[0].title,
    artist: artists[14].name,
    album: artists[14].albums[0].title,
    duration: artists[14].albums[0].songs[0].duration,
    released: artists[14].albums[0].released,
  },
  {
    id: 145,
    song: artists[2].albums[0].songs[2].title,
    artist: artists[2].name,
    album: artists[2].albums[0].title,
    duration: artists[2].albums[0].songs[2].duration,
    released: artists[2].albums[0].released,
  },
  {
    id: 146,
    song: artists[19].albums[0].songs[2].title,
    artist: artists[19].name,
    album: artists[19].albums[0].title,
    duration: artists[19].albums[0].songs[2].duration,
    released: artists[19].albums[0].released,
  },
  {
    id: 147,
    song: artists[8].albums[2].songs[5].title,
    artist: artists[8].name,
    album: artists[8].albums[2].title,
    duration: artists[8].albums[2].songs[5].duration,
    released: artists[8].albums[2].released,
  },
  {
    id: 148,
    song: artists[17].albums[1].songs[2].title,
    artist: artists[17].name,
    album: artists[17].albums[1].title,
    duration: artists[17].albums[1].songs[2].duration,
    released: artists[17].albums[1].released,
  },
  {
    id: 149,
    song: artists[6].albums[0].songs[0].title,
    artist: artists[6].name,
    album: artists[6].albums[0].title,
    duration: artists[6].albums[0].songs[0].duration,
    released: artists[6].albums[0].released,
  },
  {
    id: 150,
    song: artists[21].albums[1].songs[0].title,
    artist: artists[21].name,
    album: artists[21].albums[1].title,
    duration: artists[21].albums[1].songs[0].duration,
    released: artists[21].albums[1].released,
  },
  {
    id: 151,
    song: artists[1].albums[0].songs[4].title,
    artist: artists[1].name,
    album: artists[1].albums[0].title,
    duration: artists[1].albums[0].songs[4].duration,
    released: artists[1].albums[0].released,
  },
  {
    id: 152,
    song: artists[18].albums[2].songs[1].title,
    artist: artists[18].name,
    album: artists[18].albums[2].title,
    duration: artists[18].albums[2].songs[1].duration,
    released: artists[18].albums[2].released,
  },
  {
    id: 153,
    song: artists[16].albums[2].songs[0].title,
    artist: artists[16].name,
    album: artists[16].albums[2].title,
    duration: artists[16].albums[2].songs[0].duration,
    released: artists[16].albums[2].released,
  },
  {
    id: 154,
    song: artists[10].albums[2].songs[4].title,
    artist: artists[10].name,
    album: artists[10].albums[2].title,
    duration: artists[10].albums[2].songs[4].duration,
    released: artists[10].albums[2].released,
  },
  {
    id: 155,
    song: artists[9].albums[1].songs[0].title,
    artist: artists[9].name,
    album: artists[9].albums[1].title,
    duration: artists[9].albums[1].songs[0].duration,
    released: artists[9].albums[1].released,
  },
  {
    id: 156,
    song: artists[18].albums[3].songs[0].title,
    artist: artists[18].name,
    album: artists[18].albums[3].title,
    duration: artists[18].albums[3].songs[0].duration,
    released: artists[18].albums[3].released,
  },
  {
    id: 157,
    song: artists[21].albums[2].songs[1].title,
    artist: artists[21].name,
    album: artists[21].albums[2].title,
    duration: artists[21].albums[2].songs[1].duration,
    released: artists[21].albums[2].released,
  },
  {
    id: 158,
    song: artists[3].albums[0].songs[4].title,
    artist: artists[3].name,
    album: artists[3].albums[0].title,
    duration: artists[3].albums[0].songs[4].duration,
    released: artists[3].albums[0].released,
  },
  {
    id: 159,
    song: artists[17].albums[1].songs[1].title,
    artist: artists[17].name,
    album: artists[17].albums[1].title,
    duration: artists[17].albums[1].songs[1].duration,
    released: artists[17].albums[1].released,
  },
  {
    id: 160,
    song: artists[5].albums[0].songs[3].title,
    artist: artists[5].name,
    album: artists[5].albums[0].title,
    duration: artists[5].albums[0].songs[3].duration,
    released: artists[5].albums[0].released,
  },
  {
    id: 161,
    song: artists[1].albums[2].songs[0].title,
    artist: artists[1].name,
    album: artists[1].albums[2].title,
    duration: artists[1].albums[2].songs[0].duration,
    released: artists[1].albums[2].released,
  },
  {
    id: 162,
    song: artists[4].albums[4].songs[0].title,
    artist: artists[4].name,
    album: artists[4].albums[4].title,
    duration: artists[4].albums[4].songs[0].duration,
    released: artists[4].albums[4].released,
  },
  {
    id: 163,
    song: artists[19].albums[1].songs[2].title,
    artist: artists[19].name,
    album: artists[19].albums[1].title,
    duration: artists[19].albums[1].songs[2].duration,
    released: artists[19].albums[1].released,
  },
  {
    id: 164,
    song: artists[9].albums[1].songs[1].title,
    artist: artists[9].name,
    album: artists[9].albums[1].title,
    duration: artists[9].albums[1].songs[1].duration,
    released: artists[9].albums[1].released,
  },
];
